-- ESSENCE BARBER STUDIO V5 PREMIUM
-- Ejecutar DESPUÉS de supabase-schema.sql, supabase-v3-migration.sql y supabase-v4-upgrade.sql.
-- No contiene secretos.

alter table public.clients add column if not exists birthdate date;
alter table public.clients add column if not exists favorite_service text;
alter table public.clients add column if not exists favorite_barber text;
alter table public.clients add column if not exists visits integer not null default 0;
alter table public.clients add column if not exists total_spent numeric(12,2) not null default 0;

alter table public.products add column if not exists min_stock integer not null default 3;
alter table public.sales add column if not exists payment_method text;
alter table public.sales add column if not exists barber_name text;

create table if not exists public.cash_closures (
 id bigint generated by default as identity primary key,
 closure_date date not null default current_date,
 total_sales numeric(12,2) not null default 0,
 cash_total numeric(12,2) not null default 0,
 digital_total numeric(12,2) not null default 0,
 notes text,
 created_at timestamptz not null default now()
);

create table if not exists public.loyalty_profiles (
 client_id uuid primary key references public.clients(id) on delete cascade,
 tier text not null default 'ESSENCE' check (tier in ('ESSENCE','ESSENCE BLACK','ESSENCE VIP')),
 points integer not null default 0,
 updated_at timestamptz not null default now()
);

alter table public.cash_closures enable row level security;
alter table public.loyalty_profiles enable row level security;

do $$ begin
  create policy "auth cash closures" on public.cash_closures
  for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "auth loyalty profiles" on public.loyalty_profiles
  for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

-- Nota: el panel V5 incluye modo demo local para probar la experiencia sin Supabase.
-- Para producción, revisa RLS y evita colocar service_role/secret keys en el navegador.
