-- ESSENCE Barber Studio V4
-- Roles + shop settings + commissions + appointment workflow

create table if not exists public.shop_settings (
  id bigint generated by default as identity primary key,
  shop_name text not null default 'ESSENCE Barber Studio',
  whatsapp_number text,
  booking_message text default 'Hola, quiero reservar una cita en ESSENCE Barber Studio.',
  currency text not null default 'BOB',
  updated_at timestamptz not null default now()
);

insert into public.shop_settings (shop_name) select 'ESSENCE Barber Studio'
where not exists (select 1 from public.shop_settings);

alter table public.barbers add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.barbers add column if not exists active boolean not null default true;
alter table public.appointments add column if not exists payment_status text not null default 'Pendiente';
alter table public.appointments add column if not exists payment_method text;
alter table public.appointments add column if not exists commission_amount numeric(12,2) not null default 0;
alter table public.appointments add column if not exists confirmed_at timestamptz;
alter table public.appointments add column if not exists completed_at timestamptz;
alter table public.sales add column if not exists appointment_id bigint references public.appointments(id) on delete set null;
alter table public.sales add column if not exists payment_method text;
alter table public.sales add column if not exists commission_amount numeric(12,2) not null default 0;

create table if not exists public.staff_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null default 'barber' check (role in ('owner','admin','barber')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.shop_settings enable row level security;
alter table public.staff_profiles enable row level security;

-- Remove broad policies from earlier prototypes if present.
drop policy if exists "authenticated all" on public.shop_settings;
drop policy if exists "authenticated all" on public.staff_profiles;

create or replace function public.is_staff(required_role text default null)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.staff_profiles p
    where p.user_id = auth.uid()
      and p.active = true
      and (required_role is null or p.role = required_role or p.role in ('owner','admin'))
  );
$$;

create policy "staff can read shop settings" on public.shop_settings
for select to authenticated using (public.is_staff());
create policy "owner admin can update shop settings" on public.shop_settings
for update to authenticated using (public.is_staff('admin')) with check (public.is_staff('admin'));
create policy "staff can read profiles" on public.staff_profiles
for select to authenticated using (public.is_staff());
create policy "owner admin can manage profiles" on public.staff_profiles
for all to authenticated using (public.is_staff('admin')) with check (public.is_staff('admin'));

-- Appointment workflow: Solicitada -> Confirmada -> En curso -> Completada / Cancelada
alter table public.appointments drop constraint if exists appointments_status_check;
alter table public.appointments add constraint appointments_status_check
check (status in ('Solicitada','Confirmada','En curso','Completada','Cancelada','No asistió'));

-- Basic commission calculation trigger for completed appointments.
create or replace function public.calculate_appointment_commission()
returns trigger language plpgsql as $$
declare pct numeric := 0;
begin
  select coalesce(commission_percent,0) into pct from public.barbers where id = new.barber_id;
  if new.status = 'Completada' then
    new.commission_amount := round((coalesce(new.price,0) * pct / 100.0), 2);
    if new.completed_at is null then new.completed_at := now(); end if;
  end if;
  if new.status = 'Confirmada' and new.confirmed_at is null then new.confirmed_at := now(); end if;
  return new;
end;
$$;

drop trigger if exists trg_appointment_commission on public.appointments;
create trigger trg_appointment_commission before insert or update of status, price, barber_id on public.appointments
for each row execute function public.calculate_appointment_commission();

-- Important: do not expose secret/service-role keys in the browser.
-- Keep the publishable/anon key protected by RLS and least-privilege grants.
